# Generated by Django 3.1.4 on 2020-12-29 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_group_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_group',
            name='group_id',
        ),
        migrations.AddField(
            model_name='user_group',
            name='group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api_user.group'),
        ),
        migrations.RemoveField(
            model_name='user_group',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_group',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
